### ISSUE TITLE
How can I RUN Your req.txt

### ISSUE THREAD

**Issue by xlcbingo1999** [lethaiq/Adversarial_SocialBots_WWW22#1]
There exists too many redundant packages in your req.txt. But I can't download it via Conda.
It makes me confused to download via Pip. Can you give a simple version of ‘reqirement.txt’ for Pip and delete the redundant packages in it. Thanks

**Comment by xlcbingo1999** [comment]
`Ray` API is not suitable for current version. 
You may change your codes in  `model.py`:

```
from ray.rllib.algorithms.dqn.dqn_torch_model import DQNTorchModel
from ray.rllib.utils.torch_utils import FLOAT_MAX
from ray.rllib.utils.torch_utils import FLOAT_MIN
```

**Comment by lethaiq** [comment]
Thanks for pointing out!
