### ISSUE TITLE
Test from Pre-trained Model

### ISSUE THREAD

**Issue by aa-oo** [lethaiq/Adversarial_SocialBots_WWW22#2]
Hello, I'm sorry to bother you.When I run 'python ppo_single_large_hiar.py test ./checkpoint_best/checkpoint-150' to reproduce the results,I got the mistake 'No such file or directory: 'checkpoint_best/.tune_metadata'',it seems that the name of saved checkpoint is wrong,I feel very confused,can you tell me how can I solve this problem,thanks!

**Comment by lethaiq** [comment]
you might need to check the version of the RL library, the latest version might have added new requirements. Or you can change the checkpoint folder, but I tested and the current name should work.

**Comment by aa-oo** [comment]
Ok, thank you. I have found the problem.It's because my version of ray is incorrect.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lethaiq/Adversarial_SocialBots_WWW22"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lethaiq/Adversarial_SocialBots_WWW22] Test from Pre-trained Model (Issue #2)





 
you might need to check the version of the RL library, the latest version might have added new requirements. Or you can change the checkpoint folder, but I tested and the current name should work.
